services:
  pygeoapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: pygeoapi-testserver:prod
    container_name: pygeoapi-testserver
    ports:
      - "9500:80"
    volumes:
      - ./docker/testserver-config-prod.yml:/pygeoapi/local.config.yml:ro
    environment:
      PYGEOAPI_CONFIG: /pygeoapi/local.config.yml
      PYGEOAPI_SERVER_URL: https://testserver.urbanfuturescollective.org
    restart: unless-stopped