services:
  pygeoapi:
    build:
      context: .
      dockerfile: Dockerfile
    image: pygeoapi-growbike:prod
    container_name: pygeoapi-growbike
    ports:
      - "9000:80"
    volumes:
      - ./docker/bikebox-config-prod.yml:/pygeoapi/local.config.yml:ro
    environment:
      PYGEOAPI_CONFIG: /pygeoapi/local.config.yml
      PYGEOAPI_SERVER_URL: https://bikebox.urbanfuturescollective.org
    restart: unless-stopped
