# =================================================================
#
# Authors: Tom Kralidis <tomkralidis@gmail.com>
#
# Copyright (c) 2025 Tom Kralidis
#
# Permission is hereby granted, free of charge, to any person
# obtaining a copy of this software and associated documentation
# files (the "Software"), to deal in the Software without
# restriction, including without limitation the rights to use,
# copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the
# Software is furnished to do so, subject to the following
# conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES
# OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT
# HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY,
# WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
# OTHER DEALINGS IN THE SOFTWARE.
#
# =================================================================

server:
    bind:
        host: 0.0.0.0
        port: 5000
    url: http://localhost:5000
    mimetype: application/json; charset=UTF-8
    encoding: utf-8
    gzip: false
    languages:
        # First language is the default language
        - en-US
        - fr-CA
    # cors: true
    pretty_print: true
    limits:
        default_items: 20
        max_items: 50
    # templates:
      # path: /path/to/Jinja2/templates
      # static: /path/to/static/folder # css/js/img
    map:
        url: https://tile.openstreetmap.org/{z}/{x}/{y}.png
        attribution: '&copy; <a href="https://openstreetmap.org/copyright">OpenStreetMap contributors</a>'
    manager:
        name: TinyDB
        connection: /tmp/pygeoapi-process-manager.db
        output_dir: /tmp/
    # ogc_schemas_location: /opt/schemas.opengis.net
    admin: false # enable admin api

logging:
    level: ERROR
    #logfile: /tmp/pygeoapi.log

metadata:
    identification:
        title:
            en: pygeoapi default instance
            fr: instance par défaut de pygeoapi
        description:
            en: pygeoapi provides an API to geospatial data
            fr: pygeoapi fournit une API aux données géospatiales
        keywords:
            en:
                - geospatial
                - data
                - api
            fr:
                - géospatiale
                - données
                - api
        keywords_type: theme
        terms_of_service: https://creativecommons.org/licenses/by/4.0/
        url: http://localhost:5000
    license:
        name: CC-BY 4.0 license
        url: https://creativecommons.org/licenses/by/4.0/
    provider:
        name: Organization Name
        url: https://pygeoapi.io
    contact:
        name: Lastname, Firstname
        position: Position Title
        address: Mailing Address
        city: City
        stateorprovince: Administrative Area
        postalcode: Zip or Postal Code
        country: Country
        phone: +xx-xxx-xxx-xxxx
        fax: +xx-xxx-xxx-xxxx
        email: you@example.org
        url: Contact URL
        hours: Mo-Fr 08:00-17:00
        instructions: During hours of service. Off on weekends.
        role: pointOfContact

# resources:
#     growbike:
#         type: process
#         processor:
#             name: growbike
#         inputs:
#           cityname:
#             title: City Name
#             description: Name of the city that the analysis should be performed on. This is the query string used to fetch the data from nominatim.
#             schema:
#               type: string

#           crs_projected:
#             title: CRS projected
#             description: EPSG code of the coordinate reference system that is used to project osm data. Default is '3857' (WGS 84 / Pseudo-Mercator). If this web mercator projection is not needed, then for Europe '3035' (LAEA) and globally '54035' (Equal Earth) is better.
#             schema:
#               type: string

#           ranking:
#             title: Ranking
#             description: Method used to rank edges. Must be 'betweenness_centrality' (default), 'closeness_centrality', or 'random'.
#             schema:
#               type: string
#               default: betweenness_centrality

#           seed_point_type:
#             title: Seed point type
#             description: If set to 'auto', selects 'grid_square' or 'grid_triangle' automatically depending on the street network's orientation entropy. If set to 'grid_square', creates a square grid. If set to 'rail', uses railway stations and halts. If set to 'school', uses kindergartens, schools, colleges, and universities. If set to 'park', uses parks, gardens, nature reserves, and public bathing places.
#             schema:
#               type: string
#               default: auto

#           seed_point_grid_spacing:
#             title: Seed point grid spacing
#             description: If seed_point_type is set to 'grid_square' or 'grid_triangle', this is the spacing between seed points, in meters. Auto-value for seed_point_type 'grid_square' with seed_point_linking 'triangulate_delaunay' is 1707. Auto-value for seed_point_type 'grid_square' with seed_point_linking 'quadrangulate' is 1000. Auto-value for seed_point_type 'grid_triangle' is 1154
#             schema:
#               type: integer
#               default: auto

#           seed_point_delta:
#             title: Seed point delta
#             description: Maximum distance between raw seed points and osm nodes for snapping, in meters. Auto-value is round(seed_point_grid_spacing/4).
#             schema:
#               type: integer
#               default: auto

#           existing_network_spacing:
#             title: Existing network spacing
#             description: Spacing between seed points, in meters, only on the existing bicycle network. If not set to a positive integer, the existing network is ignored. existing_network_spacing is recommended to be smaller than seed_point_grid_spacing, ideally around 25%, to ensure that the existing bicycle network is built first.
#             schema:
#               type: integer
#               default: None

#           export_data:
#             title: Export data
#             description: always set to False since data would be stored on host machine
#             schema:
#               type: boolean
#               default: False

#         outputs:
#           result:
#             title: Growbike result
#             description: set of edges that make up newly created bicycle network. Ordering is dependent on the chosen ranking method. Each edge has attributes for length, cumulative length of the network at the step when edge gets added, and the value that is associated with the ranking method.
#             schema:
#               type: object
#               format: geojson-feature-collection
